### ISSUE TITLE
Document inheritedFleetWorkspacePermissions for Multi-User

### ISSUE THREAD

**Issue by manno** [rancher/fleet-docs#210]
```
apiVersion: management.cattle.io/v3
kind: GlobalRole
metadata:
  name: fleet-permissions
inheritedClusterRoles:
   - cluster-owner
inheritedFleetWorkspacePermissions:
  resourceRules:
    - apiGroups:
        - fleet.cattle.io
      resources:
        - clusterregistrationtokens
        - gitreporestrictions
        - clusterregistrations
        - clusters
        - gitrepos
        - bundles
        - clustergroups
      verbs:
        - "*"
  workspaceVerbs:
    - get
    - list
    - update
    - create
    - delete
    - patch
    - fleetaddcluster

rules:
- apiGroups:
  - management.cattle.io
  resources:
  - globalrolebindings
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - globalroles
  verbs:
  - delete
  - deletecollection
  - get
  - list
  - patch
  - create
  - update
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - users
  - userattribute
  - groups
  - groupmembers
  verbs:
  - '*'
```
