### ISSUE TITLE
[SURE-10124][Rancher 2.10.x] Document RBAC workaround

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet-docs#235]
SURE-10124 has a workaround (for 2.10; fixed in 2.11) which should be properly documented and mentioned in the release notes.

See SURE-10124 and https://github.com/rancher/fleet/pull/3305

**Comment by weyfonk** [comment]
For the release notes:

## Known issues

In some cases, updating Fleet may result in pre-existing GitRepos being stuck in `Git Updating` state, with a force update not resolving the issue. An error message similar to this one would appear in a git job's logs:
```
level=fatal msg="secrets \"<secret-name>\" is forbidden: User \"system:serviceaccount:fleet-default:git-<name>\" cannot delete resource \"secrets\" in API group \"\" in the namespace \"fleet-default\""
```
This is fixed in Fleet v0.12. In v0.11.8, it can be worked around as follows:
1. Edit the Kubernetes Role named after your GitRepo (`git-<gitrepo-name>`) in the same namespace as the GitRepo:
    * Under `secrets`, at the end of the Role definition: the Role should already contain permission `create`, add verbs: `get`, `update` and `delete`.
        * Before:
        ```
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
        ```

        * After:
        ```
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - create
          - update
          - delete
        ```

2. Save your changes
3. Run a "force update" on the GitRepo.
