### ISSUE TITLE
[SURE-10124][Rancher 2.9.x] Document RBAC workaround

### ISSUE THREAD

**Issue by weyfonk** [rancher/fleet-docs#248]
Backport of #235 to v2.9.9.

**Comment by weyfonk** [comment]
For the release notes:

## Known issues

In some cases, updating Fleet may result in pre-existing GitRepos being stuck in `Git Updating` state, with a force update not resolving the issue. An error message similar to this one would appear in a git job's logs:
```
level=fatal msg="secrets \"<secret-name>\" is forbidden: User \"system:serviceaccount:fleet-default:git-<name>\" cannot delete resource \"secrets\" in API group \"\" in the namespace \"fleet-default\""
```
This is fixed in Fleet v0.12. In v0.10.13, it can be worked around as follows:
1. Edit the Kubernetes Role named after your GitRepo (`git-<gitrepo-name>`) in the same namespace as the GitRepo:
    * Under `secrets`, at the end of the Role definition: the Role should already contain permission `create`, add verbs: `get`, `update` and `delete`.
        * Before:
        ```
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
        ```

        * After:
        ```
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - create
          - update
          - delete
        ```

2. Save your changes
3. Run a "force update" on the GitRepo.
