### ISSUE TITLE
Bundles dependencies in fleet.yaml: `bundleSelector` example on `dependsOn` is invalid

### ISSUE THREAD

**Issue by loicalbertin** [rancher/fleet-docs#51]
Hi :wave:!

I'm experimenting issues with the new  `dependsOn` feature in `fleet.yaml`.
I'm using fleet `v0.6.0-rc.4`

The documentation states that we could either use `name`  to specify the bundle name or `bundleSelector` to match bundle labels.

See https://github.com/rancher/fleet-docs/blob/accc99e6963cc413e7005dd4931c330254d7c21e/docs/gitrepo-structure.md?plain=1#L231-L240

While the `name` option works, `bundleSelector` does not work.

**Replacing `bundleSelector` by `selector` allows to properly match on labels.**

From my understanding this is due to https://github.com/rancher/fleet/blob/672beaad3b82fc4e318b06c2d1dc41bdf2e83f50/pkg/apis/fleet.cattle.io/v1alpha1/bundle.go#L71 

I opened the issue in the docs repos as from my POV the documentation currently does not properly reflect the code, but IMO `bundleSelector` makes more sense than just `selector`, it is coherent with `clusterSelector`. So, I can open an issue in the main fleet repository if you agree and prefer.

Thanks & have a nice day!
Loïc

**Comment by loicalbertin** [comment]
To clarify here is my working version of the fleet.yaml:

```yaml
 # dependsOn allows you to configure dependencies to other bundles. The current bundle 
 # will only be deployed, after all dependencies are deployed and in a Ready state. 
 dependsOn: 
   # Format: <GITREPO-NAME>-<BUNDLE_PATH> with all path separators replaced by "-" 
   # Example: GitRepo name "one", Bundle path "/multi-cluster/hello-world" => "one-multi-cluster-hello-world" 
   - name: one-multi-cluster-hello-world 
   # Select bundles to depend on based on their label. 
   - selector: 
       matchLabels: 
         app: weak-monkey 
```
